[package]
name = "lumvise-frontend-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
prost.workspace = true
chrono.workspace = true
json-patch = "2"
serde.workspace = true
lumvise-db-core = { workspace = true, optional = true }
serde_json.workspace = true
thiserror.workspace = true

[features]
default = []
assistant-e2e = []
desktop-app = ["dep:lumvise-db-core"]
