#[cfg(test)]
use crate::ArtifactTextVectorizer;
use crate::local::grafeo::graph_rows::{
    apply_artifact_vector_replace, prepare_artifact_vector_replace,
};
#[cfg(test)]
use crate::local::grafeo::graph_rows::{
    artifact_vector_from_node, delete_nodes_by_property, nodes_by_label_and_property,
};
use crate::local::grafeo::semantic_storage::SemanticStorage;
use crate::local::sql::validation::require_non_empty;
use crate::{Result, SemanticArtifact, StoredArtifactTextVector};

impl<'db> SemanticStorage<'db> {
    /// Upserts a text artifact and stores a generated embedding for its text.
    ///
    /// # Example
    ///
    /// ```ignore
    /// db.storage_manager().semantic_storage()
    ///     .upsert_artifact_with_vectorizer(&artifact, &vectorizer)?;
    /// ```
    #[cfg(test)]
    pub fn upsert_artifact_with_vectorizer(
        &self,
        artifact: &SemanticArtifact,
        vectorizer: &dyn ArtifactTextVectorizer,
    ) -> Result<()> {
        let vector = artifact_text(artifact)
            .map(|source_text| {
                vectorizer
                    .vectorize_artifact_text(&source_text)
                    .map(|vector| (source_text, vector))
            })
            .transpose()?;
        match vector {
            Some((source_text, vector)) => {
                self.commit_artifact_update(artifact, Some((&source_text, &vector)))
            }
            None => self.commit_artifact_update(artifact, None),
        }
    }

    /// Stores artifact content and generates an embedding for searchable text.
    ///
    /// # Example
    ///
    /// ```ignore
    /// db.storage_manager().semantic_storage()
    ///     .upsert_artifact_content_with_vectorizer(&artifact, "text/plain", b"text", &vectorizer)?;
    /// ```
    #[cfg(test)]
    pub fn upsert_artifact_content_with_vectorizer(
        &self,
        artifact: &SemanticArtifact,
        media_type: &str,
        content: &[u8],
        vectorizer: &dyn ArtifactTextVectorizer,
    ) -> Result<()> {
        require_non_empty(media_type, "non-empty media type")?;
        let artifact = self.artifact_with_content_policy(artifact, media_type, content)?;
        let vector = artifact_text(&artifact)
            .map(|source_text| {
                vectorizer
                    .vectorize_artifact_text(&source_text)
                    .map(|vector| (source_text, vector))
            })
            .transpose()?;
        match vector {
            Some((source_text, vector)) => {
                self.commit_staged_artifact_update(&artifact, Some((&source_text, &vector)))
            }
            None => self.commit_staged_artifact_update(&artifact, None),
        }
    }

    /// Stores native artifact text-vector records generated by a trusted embedding host.
    ///
    /// Each record must belong to an existing artifact and must represent that
    /// artifact's current searchable text (falling back to its inline content).
    pub fn store_artifact_text_vectors(
        &self,
        project_root: &str,
        vectors: &[StoredArtifactTextVector],
    ) -> Result<()> {
        require_non_empty(project_root, "non-empty project root")?;
        let mut writes = Vec::with_capacity(vectors.len());
        for stored in vectors {
            let artifact = self.artifact(&stored.artifact_id)?.ok_or_else(|| {
                crate::DbError::invalid_value(
                    &stored.artifact_id,
                    "existing semantic artifact for vector",
                )
            })?;
            if artifact.semantic_element_id != stored.semantic_element_id {
                return Err(crate::DbError::invalid_value(
                    &stored.artifact_id,
                    "vector semantic element id matching current artifact owner",
                ));
            }
            let owner = self
                .element(&artifact.semantic_element_id)?
                .ok_or_else(|| {
                    crate::DbError::invalid_value(
                        &artifact.semantic_element_id,
                        "existing owning semantic element for artifact",
                    )
                })?;
            if owner.project_root != project_root {
                return Err(crate::DbError::invalid_value(
                    &stored.artifact_id,
                    "semantic artifact in request project root",
                ));
            }
            let Some(source_text) = artifact_text(&artifact) else {
                return Err(crate::DbError::invalid_value(
                    &stored.artifact_id,
                    "artifact with searchable text",
                ));
            };
            if source_text != stored.source_text {
                return Err(crate::DbError::invalid_value(
                    &stored.artifact_id,
                    "vector source text matching current artifact searchable text",
                ));
            }
            if stored.vector.dimensions == 0
                || stored.vector.dimensions != stored.vector.vector.len()
                || !stored.vector.vector.iter().all(|value| value.is_finite())
            {
                return Err(crate::DbError::invalid_value(
                    &stored.artifact_id,
                    "finite vector matching declared dimensions",
                ));
            }
            writes.push((artifact, stored.source_text.as_str(), &stored.vector));
        }
        self.commit_preplanned_graph_write(
            |database| {
                writes
                    .iter()
                    .map(|(artifact, source_text, vector)| {
                        prepare_artifact_vector_replace(database, artifact, source_text, vector)
                    })
                    .collect::<Result<Vec<_>>>()
            },
            |graph, _commit_version, _collector, plans| {
                for plan in plans {
                    apply_artifact_vector_replace(graph, plan)?;
                }
                Ok(())
            },
        )
    }

    /// Reads the stored text vector for one artifact.
    ///
    /// # Example
    ///
    /// ```
    /// let db = lumvise_db_core::DbCore::in_memory().unwrap();
    /// assert!(db.storage_manager().semantic_storage().artifact_text_vector("missing").unwrap().is_none());
    /// ```
    #[cfg(test)]
    pub fn artifact_text_vector(
        &self,
        artifact_id: &str,
    ) -> Result<Option<StoredArtifactTextVector>> {
        require_non_empty(artifact_id, "non-empty semantic artifact id")?;
        Ok(self.graph.read(|graph| {
            nodes_by_label_and_property(graph, "SemanticArtifactVector", "artifact_id", artifact_id)
                .iter()
                .find_map(artifact_vector_from_node)
        }))
    }

    /// Lazily creates or refreshes the stored text vector for one artifact.
    ///
    /// # Example
    ///
    /// ```ignore
    /// let vector = db.storage_manager().semantic_storage()
    ///     .ensure_artifact_text_vector("artifact-id", &vectorizer)?;
    /// ```
    #[cfg(test)]
    pub fn ensure_artifact_text_vector(
        &self,
        artifact_id: &str,
        vectorizer: &dyn ArtifactTextVectorizer,
    ) -> Result<Option<StoredArtifactTextVector>> {
        require_non_empty(artifact_id, "non-empty semantic artifact id")?;
        let Some(artifact) = self.artifact(artifact_id)? else {
            self.remove_artifact_text_vector(artifact_id)?;
            return Ok(None);
        };
        let Some(source_text) = artifact_text(&artifact) else {
            self.remove_artifact_text_vector(artifact_id)?;
            return Ok(None);
        };
        if let Some(vector) = self.fresh_artifact_text_vector(artifact_id, &source_text)? {
            return Ok(Some(vector));
        }
        self.refresh_artifact_text_vector(&artifact, vectorizer)?;
        self.artifact_text_vector(artifact_id)
    }

    #[cfg(test)]
    pub(crate) fn remove_artifact_text_vector(&self, artifact_id: &str) -> Result<()> {
        self.commit_graph_write(|graph, _commit_version, _collector| {
            delete_nodes_by_property(graph, "SemanticArtifactVector", "artifact_id", artifact_id);
            Ok(())
        })
    }

    #[cfg(test)]
    fn refresh_artifact_text_vector(
        &self,
        artifact: &SemanticArtifact,
        vectorizer: &dyn ArtifactTextVectorizer,
    ) -> Result<()> {
        let Some(source_text) = artifact_text(artifact) else {
            self.remove_artifact_text_vector(&artifact.artifact_id)?;
            return Ok(());
        };
        let vector = vectorizer.vectorize_artifact_text(&source_text)?;
        self.commit_preplanned_graph_write(
            |database| prepare_artifact_vector_replace(database, artifact, &source_text, &vector),
            |graph, _commit_version, _collector, plan| apply_artifact_vector_replace(graph, plan),
        )
    }

    #[cfg(test)]
    fn fresh_artifact_text_vector(
        &self,
        artifact_id: &str,
        source_text: &str,
    ) -> Result<Option<StoredArtifactTextVector>> {
        let vector = self.artifact_text_vector(artifact_id)?;
        Ok(vector.filter(|vector| vector.source_text == source_text))
    }
}

fn artifact_text(artifact: &SemanticArtifact) -> Option<String> {
    artifact
        .searchable_text
        .as_deref()
        .or(artifact.content.as_deref())
        .map(str::trim)
        .filter(|text| !text.is_empty())
        .map(str::to_string)
}
