#[cfg(test)]
use crate::ArtifactTextVectorizer;
use crate::local::grafeo::graph_rows::{
    apply_element_name_vector_replace, prepare_element_name_vector_replace,
};
#[cfg(test)]
use crate::local::grafeo::graph_rows::{
    apply_element_upsert, delete_nodes_by_property, element_name_vector_from_node,
    nodes_by_label_and_property, prepare_element_upsert,
};
use crate::local::grafeo::semantic_storage::SemanticStorage;
#[cfg(test)]
use crate::local::grafeo::semantic_storage::validate_element;
use crate::local::sql::validation::require_non_empty;
use crate::{Result, SemanticElement, StoredSemanticElementNameVector};

impl<'db> SemanticStorage<'db> {
    /// Upserts a semantic element and stores a generated embedding for its name.
    ///
    /// # Example
    ///
    /// ```ignore
    /// db.storage_manager().semantic_storage()
    ///     .upsert_element_with_name_vector(&element, &vectorizer)?;
    /// ```
    #[cfg(test)]
    pub fn upsert_element_with_name_vector(
        &self,
        element: &SemanticElement,
        vectorizer: &dyn ArtifactTextVectorizer,
    ) -> Result<()> {
        validate_element(element)?;
        let source_text = element_name_text(element)?;
        let vector = vectorizer.vectorize_artifact_text(&source_text)?;
        self.commit_preplanned_graph_write(
            |database| {
                Ok((
                    prepare_element_upsert(database, element)?,
                    prepare_element_name_vector_replace(database, element, &source_text, &vector)?,
                ))
            },
            |graph, commit_version, collector, (element_plan, vector_plan)| {
                apply_element_upsert(graph, element, commit_version, element_plan)?;
                apply_element_name_vector_replace(graph, vector_plan)?;
                collector.record_element(element, crate::ChangeDisposition::Upserted);
                Ok(())
            },
        )
    }

    /// Reads the stored name vector for one semantic element.
    ///
    /// # Example
    ///
    /// ```
    /// let db = lumvise_db_core::DbCore::in_memory().unwrap();
    /// assert!(db.storage_manager().semantic_storage().element_name_vector("missing").unwrap().is_none());
    /// ```
    #[cfg(test)]
    pub fn element_name_vector(
        &self,
        semantic_element_id: &str,
    ) -> Result<Option<StoredSemanticElementNameVector>> {
        require_non_empty(semantic_element_id, "non-empty semantic element id")?;
        Ok(self.graph.read(|graph| {
            nodes_by_label_and_property(
                graph,
                "SemanticElementNameVector",
                "semantic_element_id",
                semantic_element_id,
            )
            .iter()
            .find_map(element_name_vector_from_node)
        }))
    }

    /// Stores native name-vector records generated by a trusted embedding host.
    ///
    /// Each record must belong to an existing element in `project_root` and must
    /// represent that element's current display name.
    pub fn store_element_name_vectors(
        &self,
        project_root: &str,
        vectors: &[StoredSemanticElementNameVector],
    ) -> Result<()> {
        require_non_empty(project_root, "non-empty project root")?;
        let mut writes = Vec::with_capacity(vectors.len());
        for stored in vectors {
            if stored.project_root != project_root {
                return Err(crate::DbError::invalid_value(
                    &stored.project_root,
                    "vector project root matching request project root",
                ));
            }
            let element = self.element(&stored.semantic_element_id)?.ok_or_else(|| {
                crate::DbError::invalid_value(
                    &stored.semantic_element_id,
                    "existing semantic element for vector",
                )
            })?;
            if element.project_root != project_root {
                return Err(crate::DbError::invalid_value(
                    &stored.semantic_element_id,
                    "semantic element in request project root",
                ));
            }
            if element_name_text(&element)? != stored.source_text {
                return Err(crate::DbError::invalid_value(
                    &stored.semantic_element_id,
                    "vector source text matching current element name",
                ));
            }
            if stored.vector.dimensions == 0
                || stored.vector.dimensions != stored.vector.vector.len()
                || !stored.vector.vector.iter().all(|value| value.is_finite())
            {
                return Err(crate::DbError::invalid_value(
                    &stored.semantic_element_id,
                    "finite vector matching declared dimensions",
                ));
            }
            writes.push((element, stored.source_text.as_str(), &stored.vector));
        }
        self.commit_preplanned_graph_write(
            |database| {
                writes
                    .iter()
                    .map(|(element, source_text, vector)| {
                        prepare_element_name_vector_replace(database, element, source_text, vector)
                    })
                    .collect::<Result<Vec<_>>>()
            },
            |graph, _commit_version, _collector, plans| {
                for plan in plans {
                    apply_element_name_vector_replace(graph, plan)?;
                }
                Ok(())
            },
        )
    }

    /// Lazily creates or refreshes the stored name vector for one element.
    ///
    /// # Example
    ///
    /// ```ignore
    /// db.storage_manager().semantic_storage()
    ///     .ensure_element_name_vector("element-id", &vectorizer)?;
    /// ```
    #[cfg(test)]
    pub fn ensure_element_name_vector(
        &self,
        semantic_element_id: &str,
        vectorizer: &dyn ArtifactTextVectorizer,
    ) -> Result<Option<StoredSemanticElementNameVector>> {
        require_non_empty(semantic_element_id, "non-empty semantic element id")?;
        let Some(element) = self.element(semantic_element_id)? else {
            self.remove_element_name_vector(semantic_element_id)?;
            return Ok(None);
        };
        let source_text = element_name_text(&element)?;
        if let Some(vector) = self.fresh_element_name_vector(semantic_element_id, &source_text)? {
            return Ok(Some(vector));
        }
        self.refresh_element_name_vector(&element, vectorizer)?;
        self.element_name_vector(semantic_element_id)
    }

    #[cfg(test)]
    pub(crate) fn remove_element_name_vector(&self, semantic_element_id: &str) -> Result<()> {
        self.commit_graph_write(|graph, _commit_version, _collector| {
            delete_nodes_by_property(
                graph,
                "SemanticElementNameVector",
                "semantic_element_id",
                semantic_element_id,
            );
            Ok(())
        })
    }

    #[cfg(test)]
    fn refresh_element_name_vector(
        &self,
        element: &SemanticElement,
        vectorizer: &dyn ArtifactTextVectorizer,
    ) -> Result<()> {
        let source_text = element_name_text(element)?;
        let vector = vectorizer.vectorize_artifact_text(&source_text)?;
        self.commit_preplanned_graph_write(
            |database| {
                prepare_element_name_vector_replace(database, element, &source_text, &vector)
            },
            |graph, _commit_version, _collector, plan| {
                apply_element_name_vector_replace(graph, plan)
            },
        )
    }

    #[cfg(test)]
    fn fresh_element_name_vector(
        &self,
        semantic_element_id: &str,
        source_text: &str,
    ) -> Result<Option<StoredSemanticElementNameVector>> {
        let vector = self.element_name_vector(semantic_element_id)?;
        Ok(vector.filter(|vector| vector.source_text == source_text))
    }
}

pub(crate) fn element_name_text(element: &SemanticElement) -> Result<String> {
    let text = element.name.trim();
    if !text.is_empty() {
        return Ok(text.to_string());
    }
    Err(crate::DbError::invalid_value(
        &element.semantic_element_id,
        "semantic element with non-empty name",
    ))
}
