[package]
name = "lumvise-plugin-admin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
lumvise-plugin-package.workspace = true
lumvise-plugin-runtime.workspace = true
thiserror.workspace = true

[dev-dependencies]
ed25519-dalek = "2"
hex.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true

[[bin]]
name = "lumvise-plugin-admin"
path = "src/main.rs"
